spring:
  application:
      name: api-gateway
server:
  port: 8080
  session:
       cookie:
          name: zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:gzw@localhost:1001/eureka/
  instance:
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
zuul:
  routes:
    uaa:
      path: /uaa/**
      serviceId: auth-server
  add-proxy-headers: true
ribbon:
  eureka:
    enabled: true

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      scope: read
      access-token-uri: http://localhost:8088/oauth/token
      user-authorization-uri: http://localhost:8088/oauth/authorize
    resource:
      user-info-uri: http://localhost:8088/user
      prefer-token-info: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
      - classpath:mapper/*.xml
  type-aliases-package: com.gzw.api.domain
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
